name: Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { name: "Windows MSVC", os: windows-latest, cc: "cl", cxx: "cl" }
          - { name: "Ubuntu gcc", os: ubuntu-latest, cc: "gcc", cxx: "g++" }
          - { name: "Ubuntu clang", os: ubuntu-latest, cc: "clang", cxx: "clang++" }

    steps:
    - uses: ashutoshvarma/setup-ninja@master
      with:
        version: 1.10.0
    - uses: actions/checkout@v2
      with:
        submodules: 'true'      

    - name: Check ninja-1.10.0
      run: ninja-1.10.0 --version

    - name: Use as sub-project
      if: ${{ false }}
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{ runner.workspace }}/build
        cc: ${{ matrix.config.cc }}
        cxx: ${{ matrix.config.cxx }}
        configure-options: -G Ninja -DUSE_AS=subdir
        build-type: Release

    - name: Install
      if: ${{ false }}
      uses: ashutoshvarma/action-cmake-build@master
      with:
        source-dir: bddisasm
        build-dir: ${{ runner.workspace }}/bddisasm/build
        cc: ${{ matrix.config.cc }}
        cxx: ${{ matrix.config.cxx }}
        configure-options: -G Ninja -DBDD_INCLUDE_TOOL=OFF -DCMAKE_INSTALL_PREFIX=${{ runner.workspace }}/install
        build-type: Release
        install-build: true

    - name: Use from installation
      if: ${{ false }}
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{ runner.workspace }}/build
        cc: ${{ matrix.config.cc }}
        cxx: ${{ matrix.config.cxx }}
        configure-options: -G Ninja -DUSE_AS=installed -DBDDISASM_INSTALL_PATH=${{ runner.workspace }}/install
        build-type: Release

    - name: Install in path with spaces
      if: ${{ false }}
      uses: ashutoshvarma/action-cmake-build@master
      with:
        source-dir: bddisasm
        build-dir: ${{ runner.workspace }}/bddisasm/build
        cc: ${{ matrix.config.cc }}
        cxx: ${{ matrix.config.cxx }}
        configure-options: -G Ninja -DBDD_INCLUDE_TOOL=OFF -DCMAKE_INSTALL_PREFIX="${{ runner.workspace }}/install dir"
        build-type: Release
        install-build: true

    - name: Use from installation with spaces
      if: ${{ false }}
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{ runner.workspace }}/build
        cc: ${{ matrix.config.cc }}
        cxx: ${{ matrix.config.cxx }}
        configure-options: -G Ninja -DUSE_AS=installed -DBDDISASM_INSTALL_PATH="${{ runner.workspace }}/install dir"
        build-type: Release

  build-with-vcpkg-windows:
    runs-on: windows-latest

    steps:
    - uses: ashutoshvarma/setup-ninja@master
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Prepare vcpkg
      if: ${{ false }}
      run: |
        cd vcpkg
        .\bootstrap-vcpkg.bat
        .\vcpkg.exe install bddisasm:x64-windows
        .\vcpkg.exe install bddisasm:x86-windows
        cd ..

    - name: Use with vcpkg
      if: ${{ false }}
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{ runner.workspace }}/build
        cc: cl
        cxx: cl
        configure-options: -G Ninja -DUSE_AS=vcpkg -DCMAKE_TOOLCHAIN_FILE="${{ runner.workspace }}/bddisasm-integration-test/vcpkg/scripts/buildsystems/vcpkg.cmake"
        build-type: Release
        
  build-with-vcpkg-linux:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { name: "Ubuntu gcc", os: ubuntu-latest, cc: "gcc", cxx: "g++" }
          - { name: "Ubuntu clang", os: ubuntu-latest, cc: "clang", cxx: "clang++" }

    steps:
    - uses: ashutoshvarma/setup-ninja@master
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Prepare vcpkg
      if: ${{ false }}
      run: |
        cd vcpkg
        ./bootstrap-vcpkg.sh
        ./vcpkg install bddisasm:x64-linux
        cd ..

    - name: Use with vcpkg
      if: ${{ false }}
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{ runner.workspace }}/build
        cc: cl
        cxx: cl
        configure-options: -G Ninja -DUSE_AS=vcpkg -DCMAKE_TOOLCHAIN_FILE="${{ runner.workspace }}/bddisasm-integration-test/vcpkg/scripts/buildsystems/vcpkg.cmake"
        build-type: Release
