name: CMake

on: [push]

jobs:
  Linux-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Install rapidjson
      uses: actions/checkout@master
      with:
        repository: Tencent/rapidjson
        path: rapidjson
    - name: Build dependencies
      run: |
        cd rapidjson
        mkdir _build
        cd _build
        cmake ..
        make -j$(nproc)
        sudo make install
        cd ..
        cd ..
    - name: Build
      run: |
        sudo chmod +x ./build.sh
        ./build.sh

  Winodws-build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        sdk: 10.0.18362.0
  
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
        
    - name: Build
      run: .\build.cmd
