name: vcpkg Build

on: [push]

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Build
      run: |
        sudo chmod +x ./vcpkg_build.sh
        ./vcpkg_build.sh

  windows-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Build
      run: .\build.cmd
